from parris3141/rasbpian-tf:1.3

#
# All in the context of Jupyter-guest User
#
WORKDIR /home/jupyter-guest
RUN mkdir -p ./AI-Intuition
COPY ./AI-Intuition ./AI-Intuition

#
# Filesystem to be owned by the jupyter user & group.
#
RUN chown -R :jupyter /home/jupyter-guest && \
    chown -R jupyter-guest /home/jupyter-guest && \
    chmod -R 770 /home/jupyter-guest

RUN echo '#!/bin/bash' > run-jupyter-server && \
    echo 'jupyter notebook --ip=0.0.0.0 --no-browser --port=8888' >> run-jupyter-server && \
    chmod 550 run-jupyter-server && \
    chown -R :jupyter run-jupyter-server && \
    chown -R jupyter-guest run-jupyter-server && \
    chmod -R 770 run-jupyter-server

USER jupyter-guest

CMD [/bin/bash]
